import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import { Toaster } from "@/components/ui/toaster";
import { HMSRoomProvider } from "@100mslive/react-sdk";

const locales = ["en", "de"];
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
}) {
  // Validate that the incoming `locale` parameter is valid
  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();
  return (
    <html lang={locale} suppressHydrationWarning>
      <body>
        <HMSRoomProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </HMSRoomProvider>
      </body>
    </html>
  );
}
